# Generated by Django 4.1.7 on 2023-03-01 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="имя курса")),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        help_text="Добавьте фото",
                        upload_to="course",
                        verbose_name="фото",
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
            ],
            options={"verbose_name": "курс", "verbose_name_plural": "курсы",},
        ),
        migrations.CreateModel(
            name="OrderRoadMapCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_num",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="порядковый номер",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_road_map",
                        to="course.course",
                        verbose_name="курс",
                    ),
                ),
            ],
            options={"verbose_name": "курс", "verbose_name_plural": "курсы",},
        ),
        migrations.CreateModel(
            name="RoadMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="имя дорожной карты"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="road_maps",
                        through="course.OrderRoadMapCourse",
                        to="course.course",
                        verbose_name="курсы",
                    ),
                ),
            ],
            options={
                "verbose_name": "дорожная карта",
                "verbose_name_plural": "дорожные карты",
            },
        ),
        migrations.AddField(
            model_name="orderroadmapcourse",
            name="road_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_course",
                to="course.roadmap",
                verbose_name="дорожная карта",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя урока")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ссылка на видео",
                    ),
                ),
                (
                    "methodical_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ссылка на методические материалы",
                    ),
                ),
                (
                    "order_num",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="порядковый номер",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.course",
                        verbose_name="курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ["course_id", "-order_num"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="orderroadmapcourse",
            unique_together={("course_id", "road_map_id", "order_num")},
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("methodical_url__isnull", False),
                        ("video_url__isnull", False),
                        _connector="OR",
                    )
                ),
                name="field_fullness",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson", unique_together={("course_id", "order_num")},
        ),
    ]
