# Generated by Django 4.1.7 on 2023-03-01 15:17

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course_id", "order_num"],
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.AddField(
            model_name="roadmap",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                help_text="Добавьте фото",
                null=True,
                upload_to="road_map",
                verbose_name="фото",
            ),
        ),
    ]
