# Generated by Django 4.1.7 on 2023-03-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_lesson_options_roadmap_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="текст ссылки")),
                ("link", models.URLField(verbose_name="ссылка")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="course.lesson",
                        verbose_name="урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "полезная ссылка",
                "verbose_name_plural": "полезные ссылки",
            },
        ),
    ]
