# Generated by Django 4.1.7 on 2023-03-02 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_lessonlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="описание"
            ),
        ),
    ]
